version: '3.4'

services:


  loki:
    container_name: loki
    image: grafana/loki:master
    ports:
       - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/etc/loki
    healthcheck:
        test: wget -q --tries=1 -O- http://localhost:3100/ready 
        interval: 3s
        timeout: 3s
        retries: 10
        start_period: 10s
    networks:
      - loki

  grafana:
    container_name: grafana
    image: grafana/grafana:master
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - loki
volumes:
    loki_data:
    grafana_data:
    
networks:
  loki: